require("plugins.resession.mappings")
require("plugins.lorem.mappings")
require("plugins.kommentary.mappings")
require("plugins.markview.mappings")
require("plugins.hop.mappings")
require("plugins.telescope.mappings")
require("plugins.neotree.mappings")
require("plugins.lazy.mappings")
