local macchiato = require("catppuccin.palettes").get_palette("macchiato")

return {
	"nvim-lualine/lualine.nvim",
	dependencies = { "nvim-tree/nvim-web-devicons" },
	opts = {
		options = {
			icons_enabled = false,
			theme = {
				normal = {
					a = { bg = macchiato.blue, fg = macchiato.base, gui = "bold" },
					b = { bg = macchiato.mantle, fg = macchiato.text },
					c = { bg = macchiato.surface0, fg = macchiato.text },
					x = { bg = macchiato.surface0, fg = macchiato.text },
					y = { bg = macchiato.mantle, fg = macchiato.text },
					z = { bg = macchiato.surface0, fg = macchiato.text },
				},
				insert = {
					a = { bg = macchiato.green, fg = macchiato.base, gui = "bold" },
					b = { bg = macchiato.mantle, fg = macchiato.text },
					c = { bg = macchiato.surface0, fg = macchiato.text },
					x = { bg = macchiato.surface0, fg = macchiato.text },
					y = { bg = macchiato.mantle, fg = macchiato.text },
					z = { bg = macchiato.surface0, fg = macchiato.text },
				},
				visual = {
					a = { bg = macchiato.mauve, fg = macchiato.base, gui = "bold" },
					b = { bg = macchiato.mantle, fg = macchiato.text },
					c = { bg = macchiato.surface0, fg = macchiato.text },
					x = { bg = macchiato.surface0, fg = macchiato.text },
					y = { bg = macchiato.mantle, fg = macchiato.text },
					z = { bg = macchiato.surface0, fg = macchiato.text },
				},
				replace = {
					a = { bg = macchiato.peach, fg = macchiato.base, gui = "bold" },
					b = { bg = macchiato.mantle, fg = macchiato.text },
					c = { bg = macchiato.surface0, fg = macchiato.text },
					x = { bg = macchiato.surface0, fg = macchiato.text },
					y = { bg = macchiato.mantle, fg = macchiato.text },
					z = { bg = macchiato.surface0, fg = macchiato.text },
				},
				command = {
					a = { bg = macchiato.yellow, fg = macchiato.base, gui = "bold" },
					b = { bg = macchiato.mantle, fg = macchiato.text },
					c = { bg = macchiato.surface0, fg = macchiato.text },
					x = { bg = macchiato.surface0, fg = macchiato.text },
					y = { bg = macchiato.mantle, fg = macchiato.text },
					z = { bg = macchiato.surface0, fg = macchiato.text },
				},
				inactive = {
					a = { bg = macchiato.crust, fg = macchiato.text, gui = "bold" },
					b = { bg = macchiato.crust, fg = macchiato.text },
					c = { bg = macchiato.crust, fg = macchiato.text },
				},
			},
			component_separators = "",
			section_separators = "",
			disabled_filetypes = {
				statusline = {},
				winbar = {},
			},
			ignore_focus = {},
			always_divide_middle = true,
			always_show_tabline = true,
			globalstatus = false,
			refresh = {
				statusline = 1000,
				tabline = 1000,
				winbar = 1000,
				refresh_time = 16,
				events = {
					"WinEnter",
					"BufEnter",
					"BufWritePost",
					"SessionLoadPost",
					"FileChangedShellPost",
					"VimResized",
					"Filetype",
					"CursorMoved",
					"CursorMovedI",
					"ModeChanged",
				},
			},
		},
		sections = {
			lualine_a = { "mode" },
			lualine_b = { "filename" },
			lualine_c = { { "diagnostics", icons_enabled = true } },
			lualine_x = { "lsp_status" },
			lualine_y = { "branch" },
			lualine_z = { { "location" } },
		},
		inactive_sections = {
			lualine_a = {},
			lualine_b = {},
			lualine_c = {},
			lualine_x = {},
			lualine_y = {},
			lualine_z = {},
		},
		tabline = {},
		winbar = {},
		inactive_winbar = {},
		extensions = {},
	},
}
