[[language]]
name = "python"
# uv tool install ty ruff zuban python-lsp-server
language-servers = ["ruff", "pylsp"]

[language-server.zuban]
command = "zuban"
args = ["server"]

[language-server.pylsp.config.pylsp.plugins.mypy]
# uv pip install pylsp-mypy "django-stubs[compatible-mypy]"
enabled = true
live_mode = true
strict = false


[[language]]
name = "gdscript"
language-servers = [ "godot" ]

[language-server.godot]
command = "nc"
args = [ "127.0.0.1", "6005"]

